### PR TITLE
Add slack, twitter, and forum buttons

### PR DESCRIPTION
**Pull request by BrandonJenkins14**
Add links to sites including Slack, Twitter, and OMP Forum. Addresses zowe/docs-site#863 

**Preview:** 
image

Signed-off-by: BrandonJenkins14 <36675406+BrandonJenkins14@users.noreply.github.com>

### CODE REVIEW

**Comment by jmertic** [comment]
So first off - great idea adding these links!

Thinking about it more, it could be a bit confusing on which medium to use depending upon the question or engagement one has. Could we perhaps spell this out more? Happy to brainstorm on this...

**Comment by RASakach** [comment]
HI Brandon, this looks good to me - however, I may have one small suggestion associated with another question that came up in an Onboarding meeting.  I will provide more details once I have feedback.

**Comment by jmertic** [comment]
I like the idea, but want to get some icons in here to clean it up a bit. @alexcontini - can you take a look?

**Comment by jmertic** [comment]
It looks like there are already icons in the footer for this - can we close?

**Comment by jmertic** [comment]
Thanks @BrandonJenkins14

**Pull request closed without merging**
