### PR TITLE
Add Zowe LTS information to zowe.org

### PR DESCRIPTION
**Pull request by nannanli**
Fixes: https://github.com/zowe/zlc/issues/72

**Do not merge until LTS information is ready to be published.** 

This PR contains the following changes:
- Create a **Releases** tab on zowe.org, right after the **Download** tab.
- In the new **Releases** section, added the screen capture of the LTS roadmap and the bullet points that explains the roadmap briefly.
- Added a button that links to detailed information in https://github.com/zowe/zlc/blob/master/process/ReleaseProcess.md.
- Removed the **Docs** section. Instead, made the Docs tab a direct link to the doc site. This addresses the user feedback that users have to click twice to go to the doc site on zowe.org.

Preview: 
Screen Shot 2020-02-20 at 6 07 46 PM
Screen Shot 2020-02-20 at 6 08 24 PM

Signed-off-by: nannanli <nannanli@cn.ibm.com>

@jmertic @armstro Please review and update as needed. Thanks!

### CODE REVIEW

**Comment by armstro** [comment]
@nannanli Thanks so much for fast turn around on this - comments
1) I will send email to the zlc and ask them to vote to agree to the changes 
2) I would prefer John be reviewer/approver so I don't mess it up your good work! 
3) I did notice one other change needed - what is a Zowe release - it says: A release of the Zowe project consists of two 'convenience' deliverables - CLI binaries, and a PAX file which contains the Zowe API Mediation Layer, Zowe Desktop, and Zowe Explorer-Server. ........it is now more than a PAX file and should say PAX and SMP/E files 
@jmertic asking your help

**Comment by 1000TurquoisePogs** [comment]
I can see this as a source of minor confusion.
On sites that I go to download software, I either look for "Downloads" or "Releases" here we have both.
I think it would be better if the Downloads page had this Releases explanation, so it is just 1 place that you understand & find the software.

**Comment by armstro** [comment]
Sean brings up a good point - for placement on the web page rather than having releases at the top of the page and have possible confusion with Download - how about we use the expandable sections below the downloads and have one for Support Policy?  

image

This is more consistent with how the node.js team does it too 
image

@nannanli and @Joe-Winchester ok with this?

**Comment by nannanli** [comment]
@armstro yes, that makes sense. Will make the change.

**Comment by nannanli** [comment]
Removed the Releases sections and moved the support information into the Download section. See the new design as follows. The changes are already in this PR. @armstro @Joe-Winchester @1000TurquoisePogs 

Screen Shot 2020-02-24 at 6 34 24 PM
Screen Shot 2020-02-24 at 6 37 49 PM
Screen Shot 2020-02-24 at 6 38 16 PM

**Comment by 1000TurquoisePogs** [comment]
Yeah, that looks good! Thank you for doing this.

**Comment by MikeBauerCA** [comment]
In the screenshot above, it reads "Check out the Zowe Long Term Support (TLS) schedule for releases." (TLS) should be changed to (LTS)

**Comment by nannanli** [comment]
@MikeBauerCA Thanks you for catching this! It's fixed now.

**Comment by nannanli** [comment]
@armstro Hi Bruce, is the LTS information ready to be published?

**Comment by armstro** [comment]
Ashley - there was a request to add Conformance Criteria Update to the time line chart - rather than try to explain in words where and how to note that - can you send ppt and I can modify the chart and ask the ZLC to approve. I think we are close to agreement on the LTS timeline description. 

What is unclear is the status of the new Conformance Criteria - @Joe-Winchester - at one time there was to be legal review by OMP after the criteria words were final - has that happened? It will be topic for ZLC today.

**Comment by Joe-Winchester** [comment]
@armstro - the conformance T&C document is still waiting to be merged.  https://github.com/zowe/zlc/pull/169.  13 days old.

**Comment by armstro** [comment]
@Joe-Winchester - at one time I thought we were waiting on OMP legal to approve the change to the policy (not that they have final say but something needing their input) - you say "waiting" - on who or what? 

@RASakach did this get resolved - last I saw was slack discussion https://openmainframeproject.slack.com/archives/CC60ALD61/p1583881117025000

@nannanli the requested change on the graphic was to show conformance criteria - I have attempted to edit the ppt I have......

[Zowe.OSS.2019-20.Roadmap.Rev.15 chart with dates and conformance.pptx](https://github.com/zowe/zowe.github.io/files/4348589/Zowe.OSS.2019-20.Roadmap.Rev.15.chart.with.dates.and.conformance.pptx)

**Comment by armstro** [comment]
@nannanli - at ZLC the modification I had proposed to timeline was not agreed to - @Joe-Winchester to work with on boarding squad to confirm the changes to the picture.

**Comment by nannanli** [comment]
@armstro Thank you Bruce! Will stay tuned.

**Comment by Joe-Winchester** [comment]
@armstro: we haven't yet got agreement on the conformance program being able to be updated and folks being asked to revalidate so please hold off on that chart update.  Wednesday's call was moved to Friday (tomorrow 3/20) so we should be clearer then.  cc: @RASakach

**Comment by Joe-Winchester** [comment]
@RASakach - Do you have a PDF copy of your revised LTS chart so this PR can have the latest revision ?

**Comment by Joe-Winchester** [comment]
@nannanli - for the LTS graphic can you update this PR with the diagram currently in https://github.com/zowe/zlc/issues/176 ?  Tks

**Comment by nannanli** [comment]
@Joe-Winchester @armstro The graphic has been updated. Also updated the conformance logo to use the new one. Check out this preview link: https://deploy-preview-75--condescending-dubinsky-4645a9.netlify.app/. 
To publish this, we also need to get this PR finalized and merged: https://github.com/zowe/zlc/pull/164/.

**Comment by armstro** [comment]
@Joe-Winchester 
Two comments - 
1) I am not sure "release timeline" is descriptive enough for the section ....maybe we call it "Version and Release Rollout and Support Description"......
2) There was additional slides that were agreed to - are these words included somewhere? I don't see anything on the "Learn More" link??

[Zowe.OSS.2019-20.Roadmap.Rev.12 - additional slides .pptx](https://github.com/zowe/zowe.github.io/files/4529559/Zowe.OSS.2019-20.Roadmap.Rev.12.-.additional.slides.pptx)

**Comment by nannanli** [comment]
@armstro Hi Bruce, the additional information are documented here in the release process document: https://github.com/zowe/zlc/pull/164/files. It's not merged yet and when that's merged, the Learn more link will reveal the correct details.

**Comment by nannanli** [comment]
@armstro I've updated the descriptions in the https://github.com/zowe/zlc/pull/164 to match the latest deck. You can merge it if there are no other issues. : )

**Comment by Joe-Winchester** [comment]
@nannanli - this looks good to merge now as the Zowe conformance v1 criteria are now merged.   @armstro and @RASakach - are you OK for this PR to be merged now together with https://github.com/zowe/zlc/pull/164/files ?

**Comment by armstro** [comment]
@Joe-Winchester - I think the answer is yes to merge - let's briefly discuss at ZLC today to be sure everyone is on the same page - I'm still struggling with how to review PRs but if you are ok with the words then I am fine too. 

and @RASakach

**Pull request merged**
