### PR TITLE
Add Zowe CLI Active Development Version

### PR DESCRIPTION
**Pull request by MarkAckert**
Adds Zowe CLI Active Development Version to Zowe.org. Only displays if an S3 URL is defined for the release.

### CODE REVIEW

**Comment by jmertic** [comment]
@MarkAckert Can you point to where I could see this visually to review? Thanks!

**Comment by MarkAckert** [comment]
> @MarkAckert Can you point to where I could see this visually to review? Thanks!
Hi John, I don't have this hosted anywhere to browse. If you want to build this locally, from your local clone of this repo, issue:
```
git checkout -b BrandonJenkins14-master master
git pull https://github.com/BrandonJenkins14/zowe.github.io.git master
bundle install
bundle exec jekyll serve
```
Here are screenshots of the changes on my local machine, with and without the button (based on S3 URL property):
section_without_cli_button
----
section_with_cli_button

**Comment by jmertic** [comment]
Made an adjustment to put these "not ready for primetime builds" under a collapsible section so you don't get confused with production releases. I don't love the title, so open for suggestions :-)

**Comment by MarkAckert** [comment]
In my opinion "Pre-release Builds" is a good enough title for now, I'm not sure what other alternatives we could go with. We can always adjust the title in the future

**Comment by jmertic** [comment]
I think from talking to @MarkAckert it's just file naming and getting the packaging signing done.

**Pull request merged**
