### PR TITLE
Cli active development button

### PR DESCRIPTION
**Pull request by BrandonJenkins14**
Introduce CLI Active Development (@latest) version download button. 

@MarkAckert @jackjia-ibm @zFernand0 
- Is this the correct way to introduce a release/button? 
- Can you fill in the question marks I have in `_config.yaml`? 
- Does anyone needs to add some CSS or anything else?

### CODE REVIEW

**Comment by zFernand0** [comment]
> Will a DCO signoff command help me here, or do I need to recreate this manually in another branch?

Since there is already a [dco-signoffs](https://github.com/zowe/zowe.github.io/tree/master/dco_signoffs) folder, I'm sure there could be something done about this.
If you want, you could issue this two commands against your `cli-active-development` branch
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin cli-active-development
```

**Comment by zFernand0** [comment]
Since I'm not very familiar I'd like to add a question or two as well.
1. Should the generated `_site` folder be `.gitignore`-d?
2. People that want to test in their forks have to also [setup the GH pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages) on their repo, is that true?
3. Why was there no `Gemfile` on this project if the intention is to build with Jekyll?

**Comment by jackjia-ibm** [comment]
Just my understanding, could be wrong.

- Since we have not merged into `master` yet, it's better to fix DCO sign-off before merge. Otherwise we need another PR to modify master branch `dco-signoffs` folder.
- Think if we add `_site` to `.gitignore` should make us easier. `_site` shouldn't be committed to code base.
- People want to test can follow this instruction: https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll. Option 3 is not needed in this case.
- I believe Github.io has a default Gemfile will be put into the repository, so Gemfile is not required here. Like the above instruction step 2, the Gemfile is required only if you want to build by yourself.

**Comment by zFernand0** [comment]
> Just my understanding, could be wrong.
> 
> * Since we have not merged into `master` yet, it's better to fix DCO sign-off before merge. Otherwise we need another PR to modify master branch `dco-signoffs` folder.
> * Think if we add `_site` to `.gitignore` should make us easier. `_site` shouldn't be committed to code base.
> * People want to test can follow this instruction: https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll. Option 3 is not needed in this case. `<org>.github.io` website is special comparing to other repositories. Others usually have a `gh-pages` branch, but `<org>.github.io` is configured as `Your GitHub Pages site is currently being built from the master branch.`, which doesn't have `gh-pages` branch.
> * I believe Github.io has a default Gemfile will be put into the repository when building the website, so Gemfile is not required here. Like the above instruction step 2, the Gemfile is required only if you want to build by yourself.

That being said, the Gemfile, gemfile.lock and the `_site` directory should all be ignored if that's the intention here. :smile:

**Pull request closed without merging**
