### PR TITLE
add zowe chatops to zowe.org front page

### PR DESCRIPTION
**Pull request by MarkAckert**
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>

### CODE REVIEW

**Comment by Joe-Winchester** [comment]
cc: @Phoebecdy91.  This is Mark's PR for the changes to zowe.org.

**Review by Joe-Winchester — CHANGES_REQUESTED** [review]
Instead of ChatOps can we use Chat instead ?  This matches the repository which is zowe-chat.   I think from chatting to Bruce that this was discussed at the ZAC so feel free to reach out why they didn't want ChatOps but preferred Chat instead.
I think looking at https://www.atlassian.com/blog/software-teams/what-is-chatops-adoption-guide it may be because ChatOps is more about a pipeline and automation, whereas chat is more about just issuing IO commands.

**Comment by Joe-Winchester** [comment]
@MarkAckert.     Phoebe and I were working this morning and she had a newer graphic built on yours but with a nice zoomed in area,  so we added that into the branch and also I switched `chatops` to `chat` at the same time.  @nannanli was also going to do some work on the site to swop some of the graphic->description for the projects in html to be left->right, right->left reading down the page for visual aesthetics, and also break apart the list of components at the top to separate the four core ones apart from the incubator ones.   She is a reviewer as well on this now.  Thank you !

**Comment by MarkAckert** [comment]
resolves zowe/zowe-chat#4

**Comment by MarkAckert** [comment]
Thanks for the updates Joe, I'll wait for nannanli's review

**Review by Joe-Winchester — APPROVED** [review]

**Review by nannanli — APPROVED** [review]
Looks good to me! Just a quick question. I noticed that the Slack link now directs to the #zowe-dev channel. I wonder if you want to create a zowe-chat channel instead and point users there. That could be something to do later.

**Comment by Joe-Winchester** [comment]
@nannanli ,  yes we should create our own channel once we get more momentum.  I'll bring this up at our next Zowe chat scrum call

**Pull request merged**
