### PR TITLE
Adjust the format

### PR DESCRIPTION
**Pull request by nannanli**
Signed-off-by: nannanli <nannanli@cn.ibm.com>

### CODE REVIEW

**Review by samanthasusu — APPROVED** [review]
looks good to me! thanks

**Comment by Joe-Winchester** [comment]
@balhar-jakub .    This is a great PR from @nannanli  that has put the Zowe projects into three different columns.  I wonder if Python SDK should be categorized as Incubator, and what "Under Development" means in respect to the TSC project official lifecycle ?

image

**Comment by nannanli** [comment]
@balhar-jakub Hi Jakub, this PR aims to clarify the status of Zowe components. Now we put them into 3 categories: Core, Under Development, Incubator. I wonder if this is exact or follows the Zow project maturity definition. Could you advise?

**Comment by balhar-jakub** [comment]
We have an issue there with the fact that we are mixing projects and squads.

If we are aiming on the projects then at the moment it should look like:

**LTS Core:**
Zowe Application Framework
ZSS
Zowe API Mediation Layer
Zowe CLI
Zowe Explorer

**LTS Extensions**
Zowe Explorer for IBM CICS
IBM CICS Plugin for Zowe
IBM DB2 Database Plugin
IBM ISTM Plugin
IBM MQ for z/OS plugin
z/OS FTP plugin for Zowe CLI
IMS Operations API
Zowe Explorer Extension for FTP
Zowe JavaScript SDK
Metrics Service for API ML

**Technical Preview**
Zowe Explorers for Intellij
Zowe Mobile
ZEEBRA

**Under Development**
Workflow Wizard
Zowe Python SDK
Zowe Chat


If we are interested in the squads:
**Active:**
Onboarding
Web UI
API Mediation Layer
CLI
Explorers
Systems 
Documentation

**Incubation**
zOS squad
Intellij Plugin
ZEEBRA
Chat Bot
Zowe on the go
Workflow Wizard

**Comment by balhar-jakub** [comment]
I updated the state to what is currently true: https://github.com/zowe/community/blob/master/PROJECTS.md 

But we may still need to do some more in the way of showing the data.

**Comment by balhar-jakub** [comment]
Closing, as this was done in a different way.

**Pull request closed without merging**
