### PR TITLE
zowe v1.12.0 is ready

### PR DESCRIPTION
**Pull request by jackjia-ibm**
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>

### CODE REVIEW

**Comment by jmertic** [comment]
Hey @jackjia-ibm ! I've worked with @pono and we can now host the downloads page from jFrog. Can you provide access so I can add a few assets to https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-release-local/org/zowe

**Comment by jackjia-ibm** [comment]
Sorry @jmertic my jfrog account doesn't have permission to manage users. So may need to find Andrew or Pono to create an account for you.

**Comment by jmertic** [comment]
retest

**Comment by jmertic** [comment]
Whenever netlify rebuilds this, this should be ready to test.

**Comment by jackjia-ibm** [comment]
@jmertic are we ready to merge this PR?

**Comment by jmertic** [comment]
I was more waiting for you to test and confirm @jackjia-ibm - feel free to merge once that is done.

**Comment by jackjia-ibm** [comment]
@jmertic could you help to approve the PR if you think it's ready?

**Pull request merged**
