### PR TITLE
Enhance the download section

### PR DESCRIPTION
**Pull request by nannanli**
Signed-off-by: nannanli <nannanli@cn.ibm.com>

A prototype where:
- Download is a separate page
- Clarified the relationship of the various download buttons
- Expanded the useful information such as nightly builds, etc.

### CODE REVIEW

**Comment by nannanli** [comment]
Screen captures of preview

Screen Shot 2020-06-02 at 2 01 52 AM
Screen Shot 2020-06-02 at 2 02 12 AM
Screen Shot 2020-06-02 at 2 02 34 AM
Screen Shot 2020-06-02 at 2 02 54 AM

**Comment by Joe-Winchester** [comment]
Really great improvements @nannanli so thank you for creating the new layout.  Feedback:
- At the top where there are four columns, can you group "Zowe z/OS Components" together and beneath/within that cover convenience build and SMP/E the way you have, so it's clear those are two ways to get z/OS components.  For the convenience the button says 1.11.0, but from the FMID and PTF it's not clear that the PTF is for 1.11.0 content also.
- Put links to doc chapters for each of the installers (convenience, SMP/E, and CLI) somewhere in the info text ?
- Past Releases being expanded is very nice.  Maybe name this "All Releases" and include the current release as well, so in your screen cap above 1.11.0 would be included which means at a glance a user can see the landscape of all downloads.
- For Zowe CLI would it be possible to include a link to the CLI download chapter, and include text letting users know that the CLI is available on npmjs.org, e.g. [Install CLI from on-line repository npmj.org](https://docs.zowe.org/stable/user-guide/cli-installcli.html#installing-zowe-cli-from-an-online-registry)
- The Zowe Explorer download isn't mentioned.  I wonder if it'd be possible to give it the same real estate column area as the CLI and link to the doc chapter https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html#installing.  
- Build Zowe on your own - maybe label it as "Zowe source code is available", as to do a build there are additional steps a user would need to know so it feels like we need to design and write a doc chapter specifically for this, but having the link to the repos is good

Thank you !

**Comment by nannanli** [comment]
New design: 
image
image

**Comment by nannanli** [comment]
@BrandonJenkins14 Good point. I think these two PRs can be combined to give people an overview of what the download section will look like moving forward. Will remove the pre-release build in this PR.

**Comment by nannanli** [comment]
@jmertic 
Hi John, this PR aims to redesign the Download section on zowe.org to address the feedback we've received. Not being an expert with website development, I want to get your advice on this design and how we could deliver this to benefit users asap, and if we need a designer to review this as well.  This design is a prototype and as a next step, I plan to get the community's feedback. Any feedback or advice are appreciated. 

This PR addresses the following comments:
- The download section is busy with buttons but the relationship and meaning of these buttons are not well-explained. 
- Important component like Zowe Explorer does not have much visibility in this section. 
- Many useful information such as release timeline are folded in the section and not easy to discover. 

This PR contains the following changes:
- Make **Download** a standalone page
- Reorganized the download buttons, added Zowe Explorer download, added more details about these buttons and used cards to explain the relationship. 
- Expanded information like Release timeline, previous releases, nightly builds. 
- Removed CLI Pre-Release download to incorporate #91 
- Changed the What's Zowe tab name to be **Home** for that page contains more information than what's Zowe. 
- Added a CSS link to Bootstrap

**Comment by nannanli** [comment]
@jmertic Awesome it works! Thank you for fixing all the issues in my change. I agree that a working session or design critique to review and discuss the download information will be helpful to gather input and feedback. I'm wondering if this session should go beyond just the download section to cover the whole zowe.org design so we could understand people's current experience, pain points, and ideas as a community.

**Comment by jmertic** [comment]
That's definitely one route to take, but there is a balance to strike on pragmatism in solving the problem you are looking to solve. I'm not sure if the right approach is a deeper redesign at this point, which could result from such a discussion

**Comment by 1000TurquoisePogs** [comment]
I like the second design, but need to point out that an outcome of the current PI is to make a Docker download available as a beta, so eventually there will be a 3rd option in the server-side component box. Maybe over time there will be a 4th and a 5th, etc.
If you are ok with that, then it's fine. But another option would be to have a dropdown, maybe the description changes when the dropdown changes. Not sure. Just a thought... both are fine to me.

**Comment by Joe-Winchester** [comment]
@nannanli - it looks as though you've collected a lot of great input from squad leads and others in the community and the design you have now is improved on the current layout where the buttons have no background explanation, to where they are now arranged with links to doc chapters and more information, as well as including the link to the Zowe Explorer marketplace which is great.  
@jmertic - what are the remaining steps to make this go live on zowe.org ?  It'd be great to do this concurrent with 1.13 that is in the final stages of being built and should GA within the next week.

**Pull request merged**
