### PR TITLE
Synced events with OMP website's Zowe events

### PR DESCRIPTION
**Pull request by covalentbond**
Signed-off-by: Arijit Kundu kunduarijit55@gmail.com

### CODE REVIEW

**Review by jackjia-ibm — APPROVED** [review]
Format looks good to me. Thanks!

**Comment by covalentbond** [comment]
Hey @jackjia-ibm the [latest GitHub Action](https://github.com/zowe/zowe.github.io/actions/runs/887472306) build successfully - but can you look into, why it did not create a PR. Because as you can find [here](https://github.com/zowe/zowe.github.io/blob/7c45de8e28b6610c368ccb9d70a1405cd72c38d1/.github/workflows/update_upcoming_events.yml#L38), it's expected to make a PR whenever some changes occur which can be commited.

We've been using [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) action for creating the PR. Thanks!

**Comment by jackjia-ibm** [comment]
Hi @covalentbond, I think I fixed the issues and update the workflow. Test run works ok https://github.com/zowe/zowe.github.io/runs/2711518783?check_suite_focus=true, and https://github.com/zowe/zowe.github.io/pull/142 is sample PR created.

FYI, I updated the workflow with `zowe-robot` user, so the scheduled tests will be started with that user and use correct token.

**Comment by covalentbond** [comment]
Hi, Jack! Can you please into this once: https://github.com/zowe/zowe.github.io/pull/142#discussion_r642532946

**Comment by jackjia-ibm** [comment]
https://github.com/zowe/zowe.github.io/pull/143 should fix this. https://github.com/zowe/zowe.github.io/pull/144 is example PR it created.

**Pull request closed without merging**
