### PR TITLE
Add the Explorers, CLI & SDK Office Hours

### PR DESCRIPTION
**Pull request by balhar-jakub**

### CODE REVIEW

**Review by adam-wolfe — APPROVED** [review]
LGTM

**Review by RASakach — COMMENTED** [review]
@balhar-jakub can we change the "Node SDK" topic to "Node Client SDK"?  Or will this be confusing?

**Review by RASakach — CHANGES_REQUESTED** [review]
Can we change the "Node SDK" topic to "Node Client SDK?"

**Comment by balhar-jakub** [comment]
Done

**Review by RASakach — APPROVED** [review]

**Pull request merged**
